# Generated by Django 5.1.1 on 2024-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='publication date'),
        ),
    ]
